project:
  type: book

book:
  title: "Frontify Service"
  author: "Gary Newport"
  favicon: cover.png
  date: "10/10/2025"
  sidebar: 
    background: "#F5F5F5"
    logo: cover.png
    search: true
  chapters:
    - index.qmd
    - Book/architectural-constraints/index.qmd
    - Book/system-scope-and-context/index.qmd
    - part: Book/building-block-view/building-block-view/index.qmd
      chapters:
        - Book/building-block-view/azure-function-detail/index.qmd
        - Book/building-block-view/cosmos-db-component/index.qmd
        - Book/building-block-view/domain-logic-component/index.qmd
        - Book/building-block-view/security-component/index.qmd
    - Book/solution-strategy/index.qmd
    - Book/runtime-view/index.qmd
    - Book/deployment-view/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


diagram:
  engine:
    plantuml:
      execpath: "C:/Plantuml/plantuml.bat"

filters:
  - C:/Users/NEWPORTG/source/Personal/Quarto-Frontify/_filters/inline-plantuml-input.lua
  - C:/Users/NEWPORTG/source/Personal/Quarto-Frontify/_extensions/pandoc-ext/diagram/diagram.lua
